export class RebateProgramInfoItem{
    ProgramId:string=""
    MerchantId:string=""
    ProgramName:string=""
    ProgramDescription:string=""
    ProgramImageFile:string=""
    TotalBirthdayRebatePercentage:string=""
    TotalBirthdayRebateFixedAmount:string=""
    TotalSpendingRangeRebatePercentage:string=""
    TotalSpendingRangeRebateFixedAmount:string=""
    TotalPromotionPeriodRebatePercentage:string=""
    TotalPromotionPeriodRebateFixedAmount:string=""
    TotalRebatePercentage:string=""
    TotalRebateFixedAmount:string=""
    CurrencyCode:string=""
    CurrencyCodeValue:string=""
}