export class AddNewCardModel{
    PaymentGatewayToken:string=""
    CardTypeId:string=""
    Bin:string=""
    CardProductId:string=""
    MaskedCardNumber:string=""
    CustomerId:string=""
    CardAlias:string=""
    CardHolderName:string=""
    IssuingCountryCode:string=""
    Cvv2:string=""
    RefNo:string=""
    InvoiceNo:string=""
    ApprovalCode:string=""
    ExpiryDate:string=""
    EncryptedCardInfo:string=""
}